# Generated by Django 4.1.5 on 2023-01-31 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='maincrm.loyalty'),
        ),
    ]
